### ISSUE TITLE
compilation

### ISSUE THREAD

**Issue by jtlz2** [JohannesBuchner/PolyChord#1]
So I had to add this to makefile.dep:

InitSampler.o : \
        ini.o \
        nested_sampling.o

Then I run into:

Trying to figure out how to eliminate the erroneous o..!

/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./src libchord.so
o libchord.so InitSampler.o abort.o array_utils.o calculate.o chordal_sampling.o clustering.o feedback.o generate.o ini.o mpi_utils.o nested_sampling.o params.o priors.o random_utils.o read_write.o run_time_info.o settings.o utils.o
make[1]: o: No such file or directory
make[1]: [libchord.so] Error 1 (ignored)

**Comment by jtlz2** [comment]
I think grades.F90 and evidence.f90 are also missing. I changed OBJECTS to:

OBJECTS =                    \
                  utils.o            \
                  mpi_utils.o        \
                  random_utils.o     \
                  priors.o  grades.o \
                  settings.o         \
                  calculate.o        \
                  evidence.o         \
                  feedback.o         \
                  read_write.o       \
                  clustering.o       \
                  likelihoods.o      \
                  chordal_sampling.o \
                  generate.o         \
                  nested_sampling.o  \
          InitSampler.o

Now there seem to be some subroutines missing from mpi_utils.F90 (abort) and evidence.f90?

Thanks @JohannesBuchner !

**Comment by JohannesBuchner** [comment]
Call it like this:
$ make COMPILER_TYPE=gnu MPI= libchord.so --keep-going
and again
$ make COMPILER_TYPE=gnu MPI= libchord.so 
The Makefiles do not properly handle dependencies, so it depends which files are called first.

grades.F90 and evidence.f90 do not exist anymore in v1.4. Make sure you start with a clean build directory!

**Comment by JohannesBuchner** [comment]
o is the default $(LINKLIB) (linker). ld -shared is used if you set COMPILER_TYPE=gnu. Something else would be inserted for ifort, but I don't know what.

**Comment by jtlz2** [comment]
@JohannesBuchner Works - thanks!

**Comment by jtlz2** [comment]
@JohannesBuchner This might be one for Will, but there seems to be a bug in the Fortran affecting the examples, e.g.

make gaussian

mpif90 -DMPI -I./src -I./likelihoods -I./likelihoods/examples -c polychord.F90 -lstdc++  
polychord.F90:15:39:

     use mpi_module,               only: initialise_mpi, finalise_mpi
                                       1
Error: Symbol 'initialise_mpi' referenced at (1) not found in module 'mpi_modul'
polychord.F90:15:55:

     use mpi_module,               only: initialise_mpi, finalise_mpi
                                                       1
Error: Symbol 'finalise_mpi' referenced at (1) not found in module 'mpi_module'
polychord.F90:150:33:

     output_info = NestedSampling(loglikelihood,priors,settings,MPI_COMM_WORLD) 
                                 1
Error: Interface mismatch in dummy procedure 'loglikelihood' at (1): Type mismatch in argument 'ndims' (INTEGER(4)/REAL(8))
make: *** [polychord.o] Error 1

Do you get the same?

**Comment by JohannesBuchner** [comment]
I get the error
```
mpif90 -DMPI -ffree-line-length-none -cpp  -Ofast -c utils.f90 -lstdc++  
utils.f90:990.12:

        use mpi,only: MPI_Wtime
            1
Fatal Error: Cannot read module file 'mpi.mod' opened at (1), because it was created by a different version of GNU Fortran
```

Maybe use the non-MPI version for now, via

     make COMPILER_TYPE=gnu MPI=

**Comment by jtlz2** [comment]
@JohannesBuchner OK - still left with the

cordelia:PolyChord jtlz2$ make COMPILER_TYPE=gnu MPI=
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./src libchord.a
make[1]: `libchord.a' is up to date.
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C ./likelihoods libgaussian.a
make[1]: `libgaussian.a' is up to date.
gfortran -ffree-line-length-none -cpp -fPIC -Ofast -I./src -I./likelihoods -I./likelihoods/examples -c polychord.F90 -lstdc++  
polychord.F90:152:33:

     output_info = NestedSampling(loglikelihood,priors,settings,0) 
                                 1
Error: Interface mismatch in dummy procedure 'loglikelihood' at (1): Type mismatch in argument 'ndims' (INTEGER(4)/REAL(8))
make: *** [polychord.o] Error 1
