### ISSUE TITLE
polychord compile error

### ISSUE THREAD

**Issue by 3rico** [JohannesBuchner/PolyChord#3]
when i run Make, i get the following output:

make -C ./src libchord.a
make[1]: Entering directory '/home/chege/Eric/PolyChord/src'
mpif90 -DMPI -c utils.f90 -lstdc++  
Warning: utils.f90:989: Illegal preprocessor directive
Warning: utils.f90:991: Illegal preprocessor directive
Warning: utils.f90:995: Illegal preprocessor directive
Warning: utils.f90:997: Illegal preprocessor directive
Warning: utils.f90:999: Illegal preprocessor directive
utils.f90:623:132:

         covmat = matmul(lives    - spread(mean,dim=2,ncopies=nlive) ,    transpose(lives    - spread(mean,dim=2,ncopies=nlive)    ) ) &
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
utils.f90:623:132:

         covmat = matmul(lives    - spread(mean,dim=2,ncopies=nlive) ,    transpose(lives    - spread(mean,dim=2,ncopies=nlive)    ) ) &
                                                                                                                                    1
Error: Syntax error in argument list at (1)
utils.f90:624:132:

             +    matmul(phantoms - spread(mean,dim=2,ncopies=nphantom) , transpose(phantoms - spread(mean,dim=2,ncopies=nphantom) ) )   
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
utils.f90:624:12:

             +    matmul(phantoms - spread(mean,dim=2,ncopies=nphantom) , transpose(phantoms - spread(mean,dim=2,ncopies=nphantom) ) )   
            1
Error: Unclassifiable statement at (1)
utils.f90:651:132:

         similarity_matrix = spread( [( dot_product(data_array(:,i),data_array(:,i)),i=1,size(data_array,2) )], dim=2,ncopies=size(data_array,2) )
                                                                                                                                    1
Error: Line truncated at (1) [-Werror=line-truncation]
utils.f90:651:132:

         similarity_matrix = spread( [( dot_product(data_array(:,i),data_array(:,i)),i=1,size(data_array,2) )], dim=2,ncopies=size(data_array,2) )
                                                                                                                                    1
Error: Syntax error in argument list at (1)
f951: some warnings being treated as errors
Makefile:17: recipe for target 'utils.o' failed
make[1]: *** [utils.o] Error 1
make[1]: Leaving directory '/home/chege/Eric/PolyChord/src'
Makefile:197: recipe for target 'libchord.a' failed
make: *** [libchord.a] Error 2

please help

**Comment by JohannesBuchner** [comment]
Please check the upstream project http://ccpforge.cse.rl.ac.uk/gf/project/polychord/ I think they implemented a python bridge by now.
