### ISSUE TITLE
Shared library?

### ISSUE THREAD

**Issue by qminor** [JohannesBuchner/PolyChord#5]
Is it possible to compile my C++ code and link in Polychord as a shared library so I can use the Polychord sampler from within my code? It is straightforward to do this with Multinest, but it is not clear that it can be done with Polychord. I understand that Polychord can wrap a C++ likelihood, but my code is very large and the nested sampling is just one part of it, so I would like to have the option to include Polychord as a library. Please let me know if this is possible.

Thanks,
Quinn

**Comment by JohannesBuchner** [comment]
Please don't use this repository, and use the newer upstream one instead. http://ccpforge.cse.rl.ac.uk/gf/project/polychord/
